const verses=[
['我が命に応じよ、我は真紅を纏い、我は真紅を操る者','わがめいにおうじよ、われはしんくをまとい、われはしんくをあやつるもの'],
['我が言の葉に応えよ、我の真紅は、紅き眷属の盟約に従う兵たちよ','わがことのはにこたえよ、われのしんくは、あかきけんぞくのめいやくにしたがうつわものたちよ'],
['そのとき地は傷口をひらき　流された血は赤き焔となって還る','そのときちはきずぐちをひらきながされたちはあかきほむらとなってかえる'],
['焔は野を渡り　戸口を舐め　王の衣も孤児の袖もひとしく照らす','ほむらはのをわたりとぐちをなめおうのころももこじのそでもひとしくてらす'],
['されど天の門は閉ざされたまま　ゆえに我は紅蓮を掲げ　第一の鐘を打つ','されどてんのもんはとざされたままゆえにわれはぐれんをかかげだいいちのかねをうつ'],
['鐘の音が絶えたのち　火は己が赤を焼き　深き青をあらわすであろう','かねのねがたえたのちひはおのがあかをやきふかきあおをあらわすであろう'],
['祖は海よりも深く　夜よりも静かなる青　偽りの舌を許さぬ焔なり','そはうみよりもふかくよるよりもしずかなるあおいつわりのしたをゆるさぬほむらなり'],
['その前にて七つの冠は砕け　玉座の下に隠された名は読み上げられる','そのまえにてななつのかんむりはくだけぎょくざのしたにかくされたなはよみあげられる'],
['名を奪われし者よ　顔を上げよ　汝らを裁いた者が今こそ秤に載る','なをうばわれしものよかおをあげよなれらをさばいたものがいまこそはかりにのる'],
['我はその秤に蒼き火を置く　傾いた皿が落ちるとき　第二の鐘は鳴る','われはそのはかりにあおきひをおくかたむいたさらがおちるときだいにのかねはなる'],
['その響きに天の帳は裂け　帳の向こうより白き焔が降るであろう','そのひびきにてんのとばりはさけとばりのむこうよりしろきほむらがふるであろう'],
['白き焔に手を伸べるな　此れは触れたものの終わりを告げる白なり','しろきほむらにてをのべるなこれはふれたもののおわりをつげるしろなり'],
['山は燭台のごとく溶け　川は湯気となり　海の底に死者の道があらわれる','やまはしょくだいのごとくとけかわはゆげとなりうみのそこにししゃのみちがあらわれる'],
['されば死者よ渡れ　生ける者も続け　岸のこちらに赦しは残されていない','さればししゃよわたれいけるものもつづけきしのこちらにゆるしはのこされていない'],
['最後の足が渡り終えたなら　我は白き火で岸を焼く　第三の鐘は灰となる','さいごのあしがわたりおえたならわれはしろきひできしをやくだいさんのかねははいとなる'],
['もはや鐘は鳴らずともよい　告げられるべき終わりは　すでにここに在る','もはやかねはならずともよいつげられるべきおわりはすでにここにある'],
['焔よ　残された光を喰らえ　日を呑み　月を呑み　白き己をも呑み尽くせ','ほむらよのこされたひかりをくらえひをのみつきをのみしろきおのれをものみつくせ'],
['かくして黒き火は成る　照らすものなく　照らされるものなく　ただ燃ゆるものとして','かくしてくろきひはなるてらすものなくてらされるものなくただもゆるものとして'],
['天よ　地よ　ここに汝らの名を解く　初めの言葉より前の静けさへ還れ','てんよちよここになれらのなをとくはじめのことばよりまえのしずけさへかえれ'],
['我は最後の息をもって宣する　光あれと命じた御声よ　今こそ汝が燃える番なり――黒天終焔','われはさいごのいきをもってせんするひかりあれとめいじたみこえよいまこそなれがもえるばんなりこくてんしゅうえん']];
const kana={};
['あ:a い:i,yi う:u,wu え:e お:o','か:ka き:ki く:ku,cu け:ke こ:ko,co','さ:sa し:shi,si す:su せ:se そ:so','た:ta ち:chi,ti つ:tsu,tu て:te と:to','な:na に:ni ぬ:nu ね:ne の:no','は:ha ひ:hi ふ:fu,hu へ:he ほ:ho','ま:ma み:mi む:mu め:me も:mo','や:ya ゆ:yu よ:yo','ら:ra り:ri る:ru れ:re ろ:ro わ:wa を:wo','が:ga ぎ:gi ぐ:gu げ:ge ご:go','ざ:za じ:ji,zi ず:zu ぜ:ze ぞ:zo','だ:da ぢ:di づ:du で:de ど:do','ば:ba び:bi ぶ:bu べ:be ぼ:bo','ぱ:pa ぴ:pi ぷ:pu ぺ:pe ぽ:po','ゃ:xya,lya ゅ:xyu,lyu ょ:xyo,lyo'].join(' ').split(' ').forEach(x=>{let[k,v]=x.split(':');kana[k]=v.split(',')});
for(const [k,p] of Object.entries({'き':'ky','ぎ':'gy','し':'sh,sy','じ':'j,jy,zy','ち':'ch,ty','に':'ny','ひ':'hy','び':'by','ぴ':'py','み':'my','り':'ry'}))for(const [s,v] of [['ゃ','a'],['ゅ','u'],['ょ','o']])kana[k+s]=p.split(',').map(x=>x+v).concat(kana[k].flatMap(a=>kana[s].map(b=>a+b)));
kana['、']=[','];kana['。']=['.'];
function tokens(s){let out=[];for(let i=0;i<s.length;i++){let ch=s[i];if(ch==='ん'){out.push(/[あいうえおなにぬねのやゆよ]/.test(s[i+1]||'')||i===s.length-1?['nn',"n'",'xn']:['n','nn',"n'",'xn']);continue}if(ch==='っ'){const next=kana[s.slice(i+1,i+3)]||kana[s[i+1]];if(!next)throw Error('Missing sokuon');out.push([...new Set(next.map(x=>x[0]).filter(x=>!/[aeioun]/.test(x)))].concat(['xtu','ltu','xtsu']));continue}let pair=s.slice(i,i+2);if(kana[pair]){out.push(kana[pair]);i++}else{if(!kana[ch])throw Error('Unknown '+ch);out.push(kana[ch])}}return out}
function advance(ts,states,key){let next=[];function walk(i,p){if(i>=ts.length)return;for(let word of ts[i])if(word.startsWith(p+key))next.push({i,p:p+key});if(ts[i].includes(p))walk(i+1,'')}states.forEach(s=>walk(s.i,s.p));return [...new Map(next.map(x=>[x.i+':'+x.p,x])).values()]}
const $=id=>document.getElementById(id),numbers=['一','二','三','四','五','六','七','八','九','十','十一','十二','十三','十四','十五','十六','十七','十八','十九','二十'];
const stageNames=['真紅を纏う者','紅き眷属の盟約','血の還流','地を渡る焔','第一の鐘','蒼への昇華','偽りを灼く青','七冠崩落','魂の天秤','第二の鐘','天幕裂開','白き告命','大地溶融','死者の渡り','第三の鐘','終末の静寂','喰光','黒き太陽','天地帰滅','黒天終焔'];
const colors=['#ff8357','#65c7ff','#f0eee2','#b69adf'],phases=['壱 · 紅蓮','弐 · 蒼焔','参 · 白燼','終 · 黒天'];
let mode='idle',level=0,cleared=0,ts=[],states=[],typed='',deadline=0,budget=0,totalKeys=0,soundOn=false,audio,revealTimer;
window.fx={level:0,completed:0,progress:0,pulse:0,cast:0,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches};
function bell(freq=180,duration=1,volume=.12){if(!soundOn)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();for(const multiple of [1,2.01,3.9]){let o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq*multiple;o.type='sine';g.gain.setValueAtTime(volume/multiple,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}}catch{}}
function displayInput(){const best=[...states].sort((a,b)=>b.i-a.i||b.p.length-a.p.length)[0];let rest='';if(best){rest=(ts[best.i].find(w=>w.startsWith(best.p))||'').slice(best.p.length)+ts.slice(best.i+1).map(t=>t[0]).join('')}else rest=ts.map(t=>t[0]).join('');$('roman').replaceChildren();let done=document.createElement('span');done.className='typed';done.textContent=typed;let caret=document.createElement('span');caret.className='cursor';caret.textContent=rest[0]||'';$('roman').append(done,caret,document.createTextNode(rest.slice(1)))}
function showVerse(){ts=tokens(verses[level][1]);states=[{i:0,p:''}];typed='';$('verse').textContent=verses[level][0];$('reading').textContent=verses[level][1];$('chapter').innerHTML='第'+numbers[level]+'節 <small>/ 二十節</small>';$('phase').textContent=phases[Math.floor(level/5)];document.documentElement.style.setProperty('--accent',colors[Math.floor(level/5)]);$('seals').innerHTML=Array.from({length:20},(_,i)=>'<i class="'+(i<cleared?'done':i===level?'current':'')+'"></i>').join('');budget=Math.ceil(ts.reduce((n,t)=>n+t[0].length,0)/(3+level*.065)+5);deadline=performance.now()+budget*1000;fx.level=level+1;fx.completed=cleared;fx.progress=0;$('stageMark').textContent='STAGE '+String(level+1).padStart(2,'0')+' / 20';$('stageName').textContent=stageNames[level];displayInput();$('capture').value='';}
function start(){clearTimeout(revealTimer);mode='playing';level=cleared=totalKeys=0;fx.cast=0;fx.completed=0;window.liturgyMusic?.start();document.body.style.removeProperty('--release-opacity');$('release').hidden=true;$('stageClear').textContent='';document.body.className='playing';$('startArea').hidden=true;$('result').hidden=true;$('playArea').hidden=false;$('roman').hidden=false;$('reading').hidden=false;showVerse();$('notice').textContent='一節ずつ、確かに。';$('capture').focus();bell(130,2)}
function finish(reason){if(mode!=='playing')return;mode='casting';const reached=Math.max(0,Math.ceil(cleared/5)-1);document.documentElement.style.setProperty('--accent',colors[reached]);$('phase').textContent=cleared?phases[reached]:'灰';fx.level=cleared;fx.progress=0;fx.cast=performance.now();document.body.className='playing casting';$('playArea').hidden=true;$('clock').textContent='詠唱終了';$('bar').style.transform='scaleX(0)';bell(cleared>=16?45:65+cleared*4,4,.3);$('reason').textContent=reason;const names=['不発・灰の吐息','残火','血燈','紅蓮','地を渡る焔','第一の鐘','蒼火','断罪の焔','七冠崩落','魂の天秤','第二の鐘','天幕裂開','白き告命','大地溶融','彼岸渡り','第三の鐘','終末の静寂','喰光','黒き太陽','天地帰滅','黒天終焔'];$('spell').textContent=cleared?stageNames[cleared-1]:names[0];$('release').hidden=false;$('releaseName').textContent=$('spell').textContent;$('releaseMark').textContent='RELEASE / '+String(cleared).padStart(2,'0')+' SEALS';$('releaseQuote').textContent=cleared?verses[cleared-1][0]:'消え残る火種は、次の詠唱を待つ。';window.ritualSound?.(cleared);window.liturgyMusic?.release(cleared);if(cleared===20)document.body.className+=' final-cast';$('resultText').textContent=cleared===20?'二十節、完全詠唱。光を命じた声さえ、焔の中へ。':cleared+' / 20 節を完遂。'+(cleared===0?'火はまだ、灰の底に眠る。':'最後に結んだ言葉が、魔法となって放たれた。');revealTimer=setTimeout(()=>{mode='result';$('release').hidden=true;document.body.className='playing result'+(cleared===20?' white-result':'');$('result').hidden=false;$('roman').hidden=true;$('reading').hidden=true;$('retry').focus()},cleared===20?(fx.reduced?13000:23000):(fx.reduced?2500:6500+cleared*90))}
function key(k){if(mode!=='playing')return;if(performance.now()>=deadline){finish('時間切れ — 詠唱が途絶えた');return}const next=advance(ts,states,k);if(!next.length){finish('誤入力「'+k+'」— 詠唱が途絶えた');return}states=next;typed+=k;totalKeys++;fx.progress=states.reduce((n,s)=>Math.max(n,s.i),0)/ts.length;bell(370+(totalKeys%5)*35,.06,.014);displayInput();if(states.some(s=>s.i===ts.length-1&&ts[s.i].includes(s.p))){cleared++;fx.completed=cleared;fx.pulse=performance.now();$('stageClear').textContent='STAGE '+String(cleared).padStart(2,'0')+' CLEAR · 魔法陣構築';bell(160+cleared*20,1.8,.12);if(cleared===20){finish('完全詠唱 — 二十の封印が解かれた');return}level++;showVerse();$('notice').textContent='第'+numbers[cleared-1]+'節、完遂。制限時間を更新。'}}
$('capture').addEventListener('keydown',e=>{if(e.isComposing||e.key==='Process'){ $('notice').textContent='日本語入力をOFFにして、半角英字で入力してください。';return}if(e.ctrlKey||e.metaKey||e.altKey||['Shift','Control','Alt','Meta','Tab','CapsLock'].includes(e.key))return;if(e.key==='Backspace'||e.key==='Delete'){e.preventDefault();return}if(e.key.length===1){e.preventDefault();key(e.key.toLowerCase())}});
$('capture').addEventListener('beforeinput',e=>{if(e.isComposing){e.preventDefault();$('notice').textContent='日本語入力をOFFにしてください。';return}if(e.inputType==='insertText'&&e.data){e.preventDefault();for(const c of e.data.toLowerCase())key(c)}else e.preventDefault()});$('capture').addEventListener('paste',e=>e.preventDefault());$('capture').addEventListener('compositionend',()=>{$('capture').value=''});
$('start').onclick=start;$('retry').onclick=start;$('sound').onclick=()=>{soundOn=!soundOn;$('sound').textContent='音響・BGM '+(soundOn?'ON':'OFF');$('sound').setAttribute('aria-pressed',String(soundOn));bell(160,1.2);window.liturgyMusic?.toggle()};$('motion').onclick=()=>{fx.reduced=!fx.reduced;$('motion').textContent=fx.reduced?'演出を通常に':'演出を控えめに';$('motion').setAttribute('aria-pressed',String(fx.reduced))};
function timer(){if(mode==='playing'){const left=Math.max(0,deadline-performance.now());$('clock').textContent=(left/1000).toFixed(1)+' 秒';$('bar').style.transform='scaleX('+left/(budget*1000)+')';if(!left)finish('時間切れ — 詠唱が途絶えた')}requestAnimationFrame(timer)}showVerse();fx.level=1;$('clock').textContent='待機中';requestAnimationFrame(timer);


