/* Original procedural score: "The Last Liturgy", D harmonic minor, 72 BPM.
   All voices are synthesized locally; no recordings or external audio requests. */
(()=>{
let bus,room,clock,next=0,beat=0,ending=false,voices=new Set();
const bpm=72,step=60/bpm/2,progression=[[38,45,50,53,57],[34,41,46,50,53],[31,38,43,46,50],[33,40,45,49,52]];
function setup(){audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();if(bus)return;bus=audio.createGain();bus.gain.value=0;let compressor=audio.createDynamicsCompressor();compressor.threshold.value=-22;compressor.ratio.value=5;bus.connect(compressor).connect(audio.destination);room=audio.createConvolver();let impulse=audio.createBuffer(2,audio.sampleRate*2.8,audio.sampleRate);for(let c=0;c<2;c++){let data=impulse.getChannelData(c);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*Math.pow(1-i/data.length,3)}room.buffer=impulse;let wet=audio.createGain();wet.gain.value=.28;bus.connect(room);room.connect(wet).connect(compressor)}
function tone(note,at,duration,volume,type='sine',detune=0){let o=audio.createOscillator(),g=audio.createGain(),f=audio.createBiquadFilter();o.type=type;o.frequency.value=440*Math.pow(2,(note-69)/12);o.detune.value=detune;f.type='lowpass';f.frequency.value=type==='sawtooth'?950:2400;g.gain.setValueAtTime(0,at);g.gain.linearRampToValueAtTime(volume,at+Math.min(.3,duration*.18));g.gain.exponentialRampToValueAtTime(.0001,at+duration);o.connect(f).connect(g).connect(bus);voices.add(o);o.onended=()=>{voices.delete(o);o.disconnect();f.disconnect();g.disconnect()};o.start(at);o.stop(at+duration+.05)}
function drum(at,power){let o=audio.createOscillator(),g=audio.createGain();o.frequency.setValueAtTime(95,at);o.frequency.exponentialRampToValueAtTime(29,at+.65);g.gain.setValueAtTime(power,at);g.gain.exponentialRampToValueAtTime(.0001,at+1.3);o.connect(g).connect(bus);voices.add(o);o.onended=()=>{voices.delete(o);o.disconnect();g.disconnect()};o.start(at);o.stop(at+1.4)}
function tick(){if(!soundOn||document.hidden||ending)return;while(next<audio.currentTime+.18){let stage=Math.max(1,fx.level),phase=Math.min(3,Math.floor((stage-1)/5)),bar=Math.floor(beat/8),chord=progression[bar%4];if(beat%8===0){chord.forEach((n,i)=>{tone(n,next,step*9,.032/(1+i*.15),'triangle');if(phase>=1)tone(n+12,next,step*9,.014,'sawtooth',i%2?5:-5)});tone(chord[0]-12,next,step*8,.07);drum(next,.11+phase*.025)}if(phase>=1&&beat%4===2)drum(next,.07);if(phase>=2){let n=chord[2+(beat%3)]+12;tone(n,next,step*1.8,.04,'triangle');tone(n+12,next,step*2,.014)}if(phase===3&&beat%2===0){let melody=[74,73,69,65,67,69,73,76];tone(melody[Math.floor(beat/2)%8],next,step*3,.04,'sawtooth');drum(next,.06)}beat++;next+=step}}
function start(){ending=false;beat=0;if(!soundOn)return;setup();next=audio.currentTime+.05;bus.gain.cancelScheduledValues(audio.currentTime);bus.gain.setTargetAtTime(.65,audio.currentTime,.35);clearInterval(clock);clock=setInterval(tick,70);tick()}
function silence(){clearInterval(clock);if(bus){bus.gain.cancelScheduledValues(audio.currentTime);bus.gain.setTargetAtTime(0,audio.currentTime,.08)}for(const v of voices){try{v.stop(audio.currentTime+.3)}catch{}}}
function release(n){ending=true;clearInterval(clock);if(!soundOn)return;setup();const at=audio.currentTime;bus.gain.cancelScheduledValues(at);bus.gain.setTargetAtTime(.65,at,.1);[38,45,50,53,57,62].forEach((v,i)=>tone(v,at+i*.12,n===20?8:4,.06,'triangle'));drum(at+1.35,.3);if(n===20){const end=fx.reduced?9:16;[50,57,62,65,69,74].forEach((v,i)=>tone(v,at+2+i*.3,end-3,.045,'sine'));bus.gain.setTargetAtTime(0,at+end-4,1.1)}else bus.gain.setTargetAtTime(0,at+3,1)}
window.liturgyMusic={start,release,toggle(){if(!soundOn){silence();return}if(mode==='casting'){release(fx.level)}else start()}};
document.addEventListener('visibilitychange',()=>{if(document.hidden)silence();else if(soundOn&&(mode==='playing'||mode==='idle'))start()});
})();
